package ir.ramtung.tinyme.domain.entity;

public enum MatchingOutcome {
    EXECUTED,
    NOT_ENOUGH_CREDIT,
    NOT_ENOUGH_POSITIONS,
    NOT_MET_MEQ_VALUE,
    NOT_MET_LAST_TRADE_PRICE,
    STOP_LIMIT_ORDER_IS_NOT_ALLOWED_IN_AUCTION,
    MEQ_ORDER_IS_NOT_ALLOWED_IN_AUCTION
}
